import { Property, Amenity } from '@/types'
import { Testimonial } from '@/components/public/testimonial-card'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    name: 'Luxury 3-Bedroom Penthouse',
    description:
      'Experience ultimate luxury in this stunning 3-bedroom penthouse with panoramic city views. Features include a modern kitchen, spacious living area, and exclusive access to our premium bar lounge.',
    location: 'Victoria Island, Lagos',
    nightlyRate: 45000,
    cleaningFee: 15000,
    serviceChargePercent: 10,
    capacity: {
      guests: 6,
      bedrooms: 3,
      bathrooms: 3,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'pool',
      'gym',
      'security',
      'generator',
      'bar_access',
      'tv',
      'washing_machine',
      'balcony',
    ] as Amenity[],
    hasBarAccess: true,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    ],
    status: 'active',
    cleaningTimeMinutes: 180,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Cozy 2-Bedroom Apartment',
    description:
      'Perfect for couples or small families. This cozy apartment offers comfort and convenience with modern amenities and easy access to shopping centers and restaurants.',
    location: 'Lekki Phase 1, Lagos',
    nightlyRate: 28000,
    cleaningFee: 10000,
    serviceChargePercent: 10,
    capacity: {
      guests: 4,
      bedrooms: 2,
      bathrooms: 2,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'security',
      'generator',
      'tv',
      'washing_machine',
    ] as Amenity[],
    hasBarAccess: false,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80',
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800&q=80',
    ],
    status: 'active',
    cleaningTimeMinutes: 120,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '3',
    name: 'Executive Studio with Bar Access',
    description:
      'Modern studio apartment ideal for business travelers. Features premium furnishings, high-speed internet, and complimentary access to our shared bar facility.',
    location: 'Ikeja GRA, Lagos',
    nightlyRate: 22000,
    cleaningFee: 8000,
    serviceChargePercent: 10,
    capacity: {
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'security',
      'generator',
      'bar_access',
      'tv',
    ] as Amenity[],
    hasBarAccess: true,
    images: [
      'https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=800&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80',
      'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
    ],
    status: 'active',
    cleaningTimeMinutes: 90,
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: '4',
    name: 'Spacious 4-Bedroom Family Home',
    description:
      'Perfect for families or groups. This spacious home features 4 bedrooms, a large living area, fully equipped kitchen, and private outdoor space. Includes pool and gym access.',
    location: 'Ikoyi, Lagos',
    nightlyRate: 65000,
    cleaningFee: 20000,
    serviceChargePercent: 10,
    capacity: {
      guests: 8,
      bedrooms: 4,
      bathrooms: 4,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'pool',
      'gym',
      'security',
      'generator',
      'bar_access',
      'tv',
      'washing_machine',
      'balcony',
    ] as Amenity[],
    hasBarAccess: true,
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80',
    ],
    status: 'active',
    cleaningTimeMinutes: 240,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
]

export const AMENITY_LABELS: Record<Amenity, string> = {
  wifi: 'WiFi',
  ac: 'Air Conditioning',
  parking: 'Parking',
  kitchen: 'Kitchen',
  pool: 'Swimming Pool',
  gym: 'Gym',
  security: '24/7 Security',
  generator: 'Generator',
  bar_access: 'Bar Access',
  tv: 'TV',
  washing_machine: 'Washing Machine',
  balcony: 'Balcony',
}

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    guestName: 'Chioma Adeyemi',
    guestPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
    location: 'Lagos, Nigeria',
    rating: 5,
    reviewText: 'Absolutely stunning apartment! The attention to detail was impeccable. The bar access was a fantastic touch, and the staff were incredibly welcoming. Will definitely be returning!',
    date: 'November 2024',
    propertyStayed: 'Luxury 3-Bedroom Penthouse',
  },
  {
    id: '2',
    guestName: 'David Okonkwo',
    guestPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    location: 'Abuja, Nigeria',
    rating: 5,
    reviewText: 'Perfect for my business trip to Uyo! The apartment was spotless, WiFi was excellent, and the location couldn\'t be better. Brooklyn Hills exceeded all my expectations.',
    date: 'October 2024',
    propertyStayed: 'Modern Studio Loft',
  },
  {
    id: '3',
    guestName: 'Sarah Eze',
    guestPhoto: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
    location: 'Port Harcourt, Nigeria',
    rating: 5,
    reviewText: 'My family and I had an amazing week here! The kids loved the pool, and we appreciated how well-equipped the kitchen was. True luxury at a reasonable price.',
    date: 'December 2024',
    propertyStayed: 'Executive 4-Bedroom Villa',
  },
  {
    id: '4',
    guestName: 'Emeka Johnson',
    guestPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    location: 'Enugu, Nigeria',
    rating: 5,
    reviewText: 'Outstanding service from booking to checkout. The apartment was even better than the photos! The security made me feel very safe, and the generator ensured we never lost power.',
    date: 'September 2024',
    propertyStayed: 'Cozy 2-Bedroom Apartment',
  },
  {
    id: '5',
    guestName: 'Fatima Bello',
    guestPhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80',
    location: 'Kano, Nigeria',
    rating: 5,
    reviewText: 'I travel frequently for work and this is hands down the best shortlet I\'ve stayed in. Clean, modern, and the customer service is exceptional. Highly recommended!',
    date: 'November 2024',
    propertyStayed: 'Luxury 3-Bedroom Penthouse',
  },
  {
    id: '6',
    guestName: 'Tunde Afolabi',
    guestPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
    location: 'Ibadan, Nigeria',
    rating: 5,
    reviewText: 'What a gem! The apartment was beautifully furnished and had everything we needed. The booking process was seamless, and the team was responsive to all our questions.',
    date: 'October 2024',
    propertyStayed: 'Cozy 2-Bedroom Apartment',
  },
]
