import { Property, Amenity } from '@/types'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    name: 'Luxury 3-Bedroom Penthouse',
    description:
      'Experience ultimate luxury in this stunning 3-bedroom penthouse with panoramic city views. Features include a modern kitchen, spacious living area, and exclusive access to our premium bar lounge.',
    location: 'Victoria Island, Lagos',
    nightlyRate: 45000,
    cleaningFee: 15000,
    serviceChargePercent: 10,
    capacity: {
      guests: 6,
      bedrooms: 3,
      bathrooms: 3,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'pool',
      'gym',
      'security',
      'generator',
      'bar_access',
      'tv',
      'washing_machine',
      'balcony',
    ] as Amenity[],
    hasBarAccess: true,
    images: [
      '/images/properties/property-1-1.jpg',
      '/images/properties/property-1-2.jpg',
      '/images/properties/property-1-3.jpg',
    ],
    status: 'active',
    cleaningTimeMinutes: 180,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Cozy 2-Bedroom Apartment',
    description:
      'Perfect for couples or small families. This cozy apartment offers comfort and convenience with modern amenities and easy access to shopping centers and restaurants.',
    location: 'Lekki Phase 1, Lagos',
    nightlyRate: 28000,
    cleaningFee: 10000,
    serviceChargePercent: 10,
    capacity: {
      guests: 4,
      bedrooms: 2,
      bathrooms: 2,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'security',
      'generator',
      'tv',
      'washing_machine',
    ] as Amenity[],
    hasBarAccess: false,
    images: [
      '/images/properties/property-2-1.jpg',
      '/images/properties/property-2-2.jpg',
    ],
    status: 'active',
    cleaningTimeMinutes: 120,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '3',
    name: 'Executive Studio with Bar Access',
    description:
      'Modern studio apartment ideal for business travelers. Features premium furnishings, high-speed internet, and complimentary access to our shared bar facility.',
    location: 'Ikeja GRA, Lagos',
    nightlyRate: 22000,
    cleaningFee: 8000,
    serviceChargePercent: 10,
    capacity: {
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'security',
      'generator',
      'bar_access',
      'tv',
    ] as Amenity[],
    hasBarAccess: true,
    images: [
      '/images/properties/property-3-1.jpg',
      '/images/properties/property-3-2.jpg',
    ],
    status: 'active',
    cleaningTimeMinutes: 90,
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: '4',
    name: 'Spacious 4-Bedroom Family Home',
    description:
      'Perfect for families or groups. This spacious home features 4 bedrooms, a large living area, fully equipped kitchen, and private outdoor space. Includes pool and gym access.',
    location: 'Ikoyi, Lagos',
    nightlyRate: 65000,
    cleaningFee: 20000,
    serviceChargePercent: 10,
    capacity: {
      guests: 8,
      bedrooms: 4,
      bathrooms: 4,
    },
    amenities: [
      'wifi',
      'ac',
      'parking',
      'kitchen',
      'pool',
      'gym',
      'security',
      'generator',
      'bar_access',
      'tv',
      'washing_machine',
      'balcony',
    ] as Amenity[],
    hasBarAccess: true,
    images: [
      '/images/properties/property-4-1.jpg',
      '/images/properties/property-4-2.jpg',
      '/images/properties/property-4-3.jpg',
    ],
    status: 'active',
    cleaningTimeMinutes: 240,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
]

export const AMENITY_LABELS: Record<Amenity, string> = {
  wifi: 'WiFi',
  ac: 'Air Conditioning',
  parking: 'Parking',
  kitchen: 'Kitchen',
  pool: 'Swimming Pool',
  gym: 'Gym',
  security: '24/7 Security',
  generator: 'Generator',
  bar_access: 'Bar Access',
  tv: 'TV',
  washing_machine: 'Washing Machine',
  balcony: 'Balcony',
}
